language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - "pip install -r requirements.txt"
  - "pip install selenium==2.53.6"
# command to run tests
script: 
  - "python manage.py test functional_tests"
  - "python manage.py test accounts lists"